import Header from "./componenets/Header";
import "./globals.css";
import {DM_Sans} from "next/font/google"
export const metadata = {
  title: "Coffee Listing",
  description: "Generated by create next app",
};
const dmsans = DM_Sans({ subsets: ['latin'] })

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <body
        className={`grid grid-rows-[auto_1fr_auto] min-h-screen bg-[#111315] text-base ${dmsans.className}`}
      >
        <Header/>
        <main className="flex justify-center items-center">
          {children}
        </main>
      </body>
      
    </html>
  );
}
